config/routes.rb
require 'admin_domain'

Rails.application.routes.draw do
  # Callback for omniauth oauth2
  constraints AdminDomain do
    devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  end
  scope "(:locale)", locale: /en|es/, defaults: {locale: :es} do
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines paths for admin mode
    constraints AdminDomain do
      devise_for :users, skip: :omniauth_callbacks
      #devise_for :users
      get 'admin', to: 'admin#index'
      resources :comments, only: [:create]
      resources :tags
      resources :urls do
        collection do
          get 'reload_slug'
        end
      end
      resources :users
    end

    # Defines the root path route ("/")
    root 'home#index'

    # Links routes
    get '/:slug', to: 'home#redirect', constraints: AppDomain
  end
end

app/models/url.rb
#--
#
#################################################################################
# Shortener: Generate, use, manage and analyze short URLs.
# Copyright 2023 Santiago Ramos
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#################################################################################
#
#++

class Url < ApplicationRecord
  has_and_belongs_to_many :tags
  has_many :visits, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :created_by, class_name: 'User'
  belongs_to :updated_by, class_name: 'User', optional: true

  validates :name, presence: true
  validates :original_url, presence: true 
  validates :slug, presence: true, uniqueness: true, exclusion: { in: %w(admin users tags urls), message: "%{value} is reserved." }
  validate :validate_publication_dates

  after_initialize :check_slug

  scope :enabled,-> { where(is_enabled: true) }
  scope :published, -> { enabled. 
                         where("starts_at IS NULL OR starts_at < ?", DateTime.now).
                         where("ends_at IS NULL OR ends_at > ?", DateTime.now) }

  def published?
    is_enabled && ( starts_at.nil? || starts_at < DateTime.now ) && ( ends_at.nil? || ends_at > DateTime.now )
  end

  def advanced_options?
    description.present? || starts_at || ends_at
  end

  def short_url
    AppDomain.base_url + '/' + slug
  end

  def register_visit request
    user_agent = UserAgentParser.parse(request.user_agent)
    visits.create ip_address: request.remote_ip,
                  referer: request.referer,
                  user_agent: request.user_agent,
                  browser_name: user_agent.family,
                  browser_version: user_agent.version.to_s,
                  os: user_agent.os.to_s,
                  device_brand: user_agent.device&.brand,
                  device_model: user_agent.device&.model
  end

  def qrcode
    RQRCode::QRCode.new(short_url).as_png(size: 300)
  end

  def qrcode_url
    qrcode.to_data_url
  end

  private

  def check_slug
    while self.slug.blank?
      slug_attempt = SecureRandom.alphanumeric(8).downcase
      self.slug = slug_attempt unless Url.where(slug: slug_attempt).any?
    end
  end

  def validate_publication_dates
    if starts_at.present? && ends_at.present? && starts_at > ends_at
      errors.add :base, "starting date can't be after endind date"
    end
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_url, only: [:show, :edit, :update, :destroy]

  def index
    @urls = Url.reorder(:name).page params[:page]
  end

  def show
  end

  def new
    @url = Url.new
    @tags = Tag.order(:name)
  end

  def edit
    @tags = Tag.order(:name)
  end

  def create
    @url = Url.new(url_params)
    @url.created_by = current_user
    if @url.save
      flash[:notice] = t('urls.messages.removed')
      redirect_to @url
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @url.updated_by = current_user
    if @url.update(url_params)
      flash[:notice] = t('urls.messages.updated')
      redirect_to @url
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @url.destroy
    if @url.errors.empty?
      flash[:notice] = t('urls.messages.removed')
    else
      flash[:alert] = @url.errors.full_messages
    end
    redirect_to urls_url, status: :see_other
  end

  def reload_slug
    url = Url.new
    render json: url.slug.to_json
  end
  
  private

  def get_url
    @url = Url.find(params[:id])
  end

  def url_params
    params.require(:url).permit( :name, :description, :slug, :original_url,
                                 :is_enabled, :starts_at, :ends_at,
                                 {tag_ids: []} )
  end

end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/urls/_form.html.erb
<%= form_with(model: url) do |form| %>
  <div class="card-body">
    <%= errors @url %>

    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

        <div class="form-group row">
          <div class="col-lg-9 col-md-12 col-sm-12 col-xs-12">
            <%= form.text_field :name, class: 'form-control form-control-border', autocomplete: 'off', placeholder: t('urls.form.placeholder.name'), required: true %>
          </div>
          <div class="col-lg-3 col-md-12 col-sm-12 col-xs-12">
            <div class="custom-control custom-switch float-left mt-2 float-lg-right">
              <%= form.check_box :is_enabled, class: 'form-control custom-control-input' %>
              <%= form.label :is_enabled, class: 'control-label custom-control-label text-muted' %>
            </div>
          </div>
        </div>
        
        <div class="input-group mb-3" data-controller="urls">
          <div class="input-group-prepend">
            <span class="input-group-text"><%= AppDomain.base_url %>/</span>
          </div>

          <%= form.text_field :slug, 'data-urls-target': 'slug', class: 'form-control', autocomplete: 'off', placeholder: t('urls.form.placeholder.slug'), required: true %>
          <a data-action="click->urls#reload_slug", class="btn btn-sm btn-default pt-2 px-3" title="<%= t('urls.form.action.slug-reload') %>">
            <%= fa_icon 'rotate-right' %>
          </a>
        </div>

        <div class="form-group row">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <%= form.text_field :original_url, class: 'form-control form-control-border', autocomplete: 'off', placeholder: t('urls.form.placeholder.original_url'), required: true %>
          </div>
        </div>

        <%= render partial: 'tags', locals: {form: form} %>
        <div class="accordion active" id="accordionAdvancedOptions">
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
              <button class="accordion-button <%= 'collapsed' unless @url.advanced_options? %>" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOptions" aria-expanded="false" aria-controls="collapseOptions">
                <%= I18n.t('urls.form.action.advanced-options') %>
              </button>
            </h2>

            <div id="collapseOptions" class="accordion-collapse collapse <%= 'show' if @url.advanced_options? %>" aria-labelledby="headingOne" data-bs-parent="#accordionAdvancedOptions">
              <div class="accordion-body">
                <div class="form-group row">
                  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <%= form.text_area :description, class: 'form-control form-control-border', autocomplete: 'off', placeholder: t('urls.form.placeholder.description'), required: false %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <%= form.datetime_field :starts_at, class: 'form-control form-control-border', placeholder: t('urls.form.placeholder.starts_at'), required: false %>
                    <small class="text-muted"><%= t('urls.form.placeholder.starts_at') %></small>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <%= form.datetime_field :ends_at, class: 'form-control form-control-border', placeholder: t('urls.form.placeholder.ends_at'), required: false %>
                    <small class="text-muted"><%= t('urls.form.placeholder.ends_at') %></small>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="card-footer">
    <div class="form-action">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <%= link_to t('actions.list'), urls_path, class: 'btn btn-secondary' %>

          <div class="float-right">
            <%= form.submit (%w(edit update).include?(action_name) ? t('actions.update') : t('actions.save')), class: 'btn btn-primary' %>
            <%= link_to t('actions.show'), @url, class: 'btn btn-default' if %w(edit update).include?(action_name) %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/urls/_tags.html.erb
      <div class="form-group row">
        <div class="accordion active" id="accordionTags">
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingTags">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTags" aria-expanded="false" aria-controls="collapseTags">
                <%= I18n.t('urls.form.action.tags') %>
              </button>
            </h2>

            <div id="collapseTags" class="accordion-collapse collapse" aria-labelledby="headingTags" data-bs-parent="#accordionTags">
              <div class="accordion-body">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <%= form.collection_select :tag_ids, @tags, :id, :name, {}, { multiple: true, class: "col-lg-12" } %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

app/views/urls/edit.html.erb
<!-- Content -->
<section class="content pt-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-12 col-xs-12">
        <div class="card card-primary">
          <div class="card-header">
            <span class="card-title"><%= t 'urls.form.title.edit' %></h3>
          </div>
          
          <%= render 'form', url: @url %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/urls/index.html.erb
<!-- Content Header -->
<% if current_user %>
  <section class="content-header pt-4">
    <div class="container">
      <div class="row mb-2">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <h1 class="m-0 float-left"><%= t 'urls.actions.list' %></h1>
          <%= link_to t('urls.actions.new'), new_url_path, class: 'btn btn-primary float-right' %>
        </div>
      </div>
    </div>
  </section>

  <!-- Content -->
  <section class="content">
    <div class="container" id="users-list">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <table class="table">
            <thead>
              <tr>
                <th><%= t('urls.attributes.name') %></th>
                <th class="d-none d-sm-table-cell"><%= t('urls.attributes.original_url') %></th>
                <th><%= t('urls.attributes.published') %></th>
                <th class="d-none d-sm-table-cell"><%= t('urls.attributes.created_by') %></th>
                <th><span class="sr-only"><%= t('actions.actions') %></span></th>
              </tr>
            </thead>
            <tbody>
              <% @urls.each do |url| %>
                <tr>
                  <td><%= url.name %></td>
                  <td class="d-none d-sm-table-cell"><%= url.original_url %></td>
                  <td><%= t "#{url.published?}" %></td>
                  <td class="d-none d-sm-table-cell"><%= url.created_by&.username %></td>
                  <td class="col-1 text-nowrap">
                    <div class="float-right">
                      <%= link_to '', url_path(url), class: 'mx-1 fa fa-eye', title: t('urls.actions.show') %>
                      <%= link_to '', edit_url_path(url), class: 'mx-1 fa fa-edit', title: t('urls.actions.edit') %>
                      <%= link_to '', url_path(url), data: { turbo_method: :delete, turbo_confirm: t('urls.actions.confirm-destroy')%{url: url.name} }, class: 'mx-1 text-danger fa fa-times', title: t('urls.actions.destroy') %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="paginate">
            <small><%= page_entries_info @urls, entry_name: '' %></small>
            <div class="pagination pagination-sm">
              <%= paginate @urls %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/urls/new.html.erb
<!-- Content -->
<section class="content pt-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-12 col-xs-12">
        <div class="card card-primary">
          <div class="card-header">
            <span class="card-title"><%= t 'urls.form.title.new' %></h3>
          </div>
          
          <%= render 'form', url: @url %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/urls/show.html.erb
<!-- Content -->
<section class="content pt-2">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card card-primary">
          <div class="card-header">
            <span class="card-title"><%= t('models.url.one') + ': ' + @url.name %></h3>
          </div>

          <div class="card-body row">
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
              <dl class="row">
                <dt class="col-sm-3"><%= I18n.t('urls.attributes.slug') %></dt>
                <dd class="col-sm-9"><%= @url.short_url %></dd>

                <dt class="col-sm-3"><%= I18n.t('urls.attributes.original_url') %></dt>
                <dd class="col-sm-9"><%= @url.original_url %></dd>

                <dt class="col-sm-3"><%= I18n.t('urls.attributes.published') %></dt>
                <dd class="col-sm-9"><%= I18n.t(@url.published?) %></dd>

                <dt class="col-sm-3"><%= I18n.t('urls.attributes.is_enabled') %></dt>
                <dd class="col-sm-9"><%= I18n.t(@url.is_enabled) %></dd>

                <dt class="col-sm-3"><%= I18n.t('urls.attributes.description') %></dt>
                <dd class="col-sm-9"><%= @url.description || '---' %></dd>

                <% if @url.tags.any? %>
                  <dt class="col-sm-3"><%= I18n.t('urls.attributes.tags') %></dt>
                  <dd class="col-sm-9"><%= @url.tags.collect{|t| link_to(t.name, tag_url(t))}.join(', ').html_safe %></dd>
                <% end %>

                <% if @url.starts_at %>
                  <dt class="col-sm-3"><%= I18n.t('urls.attributes.starts_at') %></dt>
                  <dd class="col-sm-9"><%= I18n.l(@url.starts_at) %></dd> 
                <% end %>
                
                <% if @url.ends_at %>
                  <dt class="col-sm-3"><%= I18n.t('urls.attributes.ends_at') %></dt>
                  <dd class="col-sm-9"><%= I18n.l(@url.ends_at) %></dd> 
                <% end %>

                <dt class="col-sm-3"><%= I18n.t('urls.attributes.created_by') %></dt>
                <dd class="col-sm-9">
                  <% if @url.created_by %>
                    <%= current_user.is_admin? ? link_to(@url.created_by.username, user_url(@url.created_by)) : @url.created_by.username %>
                  <% else %>
                    <%= I18n.t('users.messages.unknown-user') %>
                  <% end %>
                </dd>

                <dt class="col-sm-3"><%= I18n.t('urls.attributes.created_at') %></dt>
                <dd class="col-sm-9"><%= I18n.l(@url.created_at) %></dd>

                <% if @url.updated_by_id %>
                  <dt class="col-sm-3"><%= I18n.t('urls.attributes.updated_by') %></dt>
                  <dd class="col-sm-9"><%= @url.updated_by&.username || '---' %></dd>

                  <dt class="col-sm-3"><%= I18n.t('urls.attributes.updated_at') %></dt>
                  <dd class="col-sm-9"><%= I18n.l(@url.updated_at) %></dd>
                <% end %>
              </dl>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
              <div class="text-center">
                <%= image_tag @url.qrcode_url, class: 'img-thumbnail mb-2' %>
              </div>
            </div>
          </div>

          <div class="card-footer">
            <div class="form-action">
              <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  
                  <%= link_to t('actions.list'), urls_path, class: 'btn btn-secondary' %>

                  <div class="float-right">
                    <%= link_to t('actions.edit'), edit_url_path(@url), class: 'btn btn-primary' %>
                    <%= link_to t('urls.actions.destroy'), url_path(@url), data: { turbo_method: :delete, turbo_confirm: t('urls.actions.confirm-destroy')%{url: @url.name} }, class: 'btn btn-danger', title: t('urls.actions.destroy') %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render partial: 'visits/statistics', locals: {object: @url} %>
    <%= render partial: 'comments/comments', locals: {object: @url} %>
  </div>
</section>