config/routes.rb
require 'admin_domain'

Rails.application.routes.draw do
  # Callback for omniauth oauth2
  constraints AdminDomain do
    devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  end
  scope "(:locale)", locale: /en|es/, defaults: {locale: :es} do
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines paths for admin mode
    constraints AdminDomain do
      devise_for :users, skip: :omniauth_callbacks
      #devise_for :users
      get 'admin', to: 'admin#index'
      resources :comments, only: [:create]
      resources :tags
      resources :urls do
        collection do
          get 'reload_slug'
        end
      end
      resources :users
    end

    # Defines the root path route ("/")
    root 'home#index'

    # Links routes
    get '/:slug', to: 'home#redirect', constraints: AppDomain
  end
end

app/views/admin/index.html.erb
  <!-- Content -->
  <section class="content">
    <div class="container" id="admin-page">
      <div class="row text-center">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 pt-2">
          <a href="<%= urls_url %>" class="link-dark" title="<%= t('admin.urls.title') %>">
            <div class="card card-primary">
              <div class="card-body">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 m-2">
                  <p><i class="fa fa-cloud w3-margin-bottom w3-text-theme" style="font-size:60px"></i></p>
                  <h3><%= t('admin.urls.count', count: Url.enabled.count) %></h3>
                </div>
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 pt-2">
          <a href="<%= tags_url %>" class="link-dark" title="<%= t('admin.tags.title') %>">
            <div class="card card-primary">
              <div class="card-body">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 m-2">
                  <p><i class="fa fa-tags w3-margin-bottom w3-text-theme" style="font-size:60px"></i></p>
                  <h3><%= t('admin.tags.count', count: Tag.count) %></h3>
                </div>
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 pt-2">
          <a href="<%= users_url %>" class="link-dark" title="<%= t('admin.users.title') %>">
            <div class="card card-primary">
              <div class="card-body">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 m-2">
                  <p><i class="fa fa-user w3-margin-bottom w3-text-theme" style="font-size:60px"></i></p>
                  <h3><%= t('admin.users.count', count: User.enabled.count) %></h3>
                </div>
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 pt-2">
          <div class="card card-primary">
            <a href="<%= urls_url %>" class="link-dark" title="<%= t('admin.visits.title') %>">
              <div class="card-body">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 m-2">
                  <p><i class="fa fa-signal w3-margin-bottom w3-text-theme" style="font-size:60px"></i></p>
                  <h3><%= t('admin.visits.count', count: Visit.count) %></h3>
                </div>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="row text-center">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 pt-2">
          <div class="card card-secondary">
            <div class="card-header">
              <span class="card-title"><%= t('admin.graph.title') %></span>
            </div>
            <% months = 3 %>
            <div class="card-body text-center">
              <% visits = Visit.where('created_at > ?', Time.now - months.months) %>
              <%= line_chart visits.group_by_day(:created_at).count, download: {filename: t('admin.graph.title').downcase.gsub(' ','_')} %>
              <br><p><%= t('admin.graph.subtitle', count: visits.count, months: months) %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>