config/routes.rb
require 'admin_domain'

Rails.application.routes.draw do
  # Callback for omniauth oauth2
  constraints AdminDomain do
    devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  end
  scope "(:locale)", locale: /en|es/, defaults: {locale: :es} do
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines paths for admin mode
    constraints AdminDomain do
      devise_for :users, skip: :omniauth_callbacks
      #devise_for :users
      get 'admin', to: 'admin#index'
      resources :comments, only: [:create]
      resources :tags
      resources :urls do
        collection do
          get 'reload_slug'
        end
      end
      resources :users
    end

    # Defines the root path route ("/")
    root 'home#index'

    # Links routes
    get '/:slug', to: 'home#redirect', constraints: AppDomain
  end
end

app/models/user.rb
#--
#
#################################################################################
# Shortener: Generate, use, manage and analyze short URLs.
# Copyright 2023 Santiago Ramos
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#################################################################################
#
#++

class User < ApplicationRecord
  devise :database_authenticatable, :lockable,
         :recoverable, :rememberable, :validatable,
         :trackable, :timeoutable,
         :omniauthable, omniauth_providers: [:google_oauth2, :custom_oauth2]

  has_many :urls, foreign_key: :created_by_id, dependent: :nullify
  has_many :updated_urls, class_name: 'Url', foreign_key: :updated_by_id, dependent: :nullify
  has_many :tags, foreign_key: :created_by_id, dependent: :nullify
  has_many :updated_tags, class_name: 'Tag', foreign_key: :updated_by_id, dependent: :nullify
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :commentaries, class_name: 'Comment', foreign_key: :created_by_id, dependent: :nullify

  validates :username, presence: true, uniqueness: true

  scope :enabled,-> { where(is_enabled: true) }

  def self.from_omniauth(auth)
    Rails.logger.info "[User.from_omniauth] #{auth.inspect}"
    if user = find_by(email: auth.info.email, is_enabled: true)
      if (user.provider.nil? && user.uid.nil?) || (user.provider == auth.provider.to_s && user.uid == auth.uid.to_s)
        user.update provider: auth.provider, uid: auth.uid,
                    username: auth.info.name, avatar_url: auth.info.image
      else
        user = nil
      end
    end
    return user
  end

  def active_for_authentication?
    super and self.is_enabled?
  end

  def password_required?
    new_record? ? false : super
  end

  # Alias method
  def name
    username
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def custom_oauth2
    Rails.logger.info "[Users::OmniauthCallbackController.custom_oauth2]"
    if ENV['OAUTH2_PROVIDER_URL'].present? && ENV['OAUTH2_CLIENT_ID'].present? && ENV['OAUTH2_CLIENT_SECRET'].present?
      common_callback 'devise.custom_provider_data'
    else
      message = 'Client and secred tokens for Custom OAuth2 missing'
      Rails.logger.error "[Users::OmniauthCallbacksController.custom_oauth2] ERROR: " + message
      redirect_to new_user_session_url, alert: message 
    end
  end

  def google_oauth2
    Rails.logger.info "[Users::OmniauthCallbackController.google_oauth2]"
    if ENV['GOOGLE_CLIENT_ID'].present? && ENV['GOOGLE_CLIENT_SECRET'].present?
      common_callback 'devise.google_data'
    else
      message = 'Client and secred tokens for Google OAuth2 missing'
      Rails.logger.error "[Users::OmniauthCallbacksController.google_oauth2] ERROR: " + message
      redirect_to new_user_session_url, alert: message 
    end
  end

  def failure
    Rails.logger.info "[Users::OmniauthCallbackController.failure"
    Rails.logger.error "[Users::OmniauthCallbacksController.failure] ERROR!!!"
    redirect_to root_path
  end

  private

  def common_callback session_store
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user && @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success'
      sign_in_and_redirect @user, event: :authentication
    else
      # Set session info
      request_auth = request.env['omniauth.auth'].except('extra') # removing extra as it can overflow some session stores
      session[session_store] = request_auth
      message = @user ? t('devise.sessions.oauth2.error.disabled') : t('devise.sessions.oauth2.error.not-found')
      Rails.logger.error "[Users::OmniauthCallbacksController.common_callback] ERROR: " + message
      redirect_to new_user_session_url, alert: message
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :only_for_admin!, only: [:index, :new, :create, :destroy]
  before_action :get_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.reorder(:username).page params[:page]
  end

  def show
    only_for_admin! if current_user != @user
  end

  def new
    @user = User.new
  end

  def edit
    only_for_admin! if current_user != @user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = t('users.messages.created')
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    only_for_admin! if current_user != @user
    if ( user_params[:password].blank? && user_params[:password_confirmation].blank? ?
         @user.update_without_password(user_params) :
         @user.update(user_params)
       )
      flash[:notice] = t('users.messages.updated')
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if current_user != @user
      @user.destroy
    else
      flash[:alert] = t('users.errors.destroy.own-user')
    end
    if @user.errors.empty?
      flash[:notice] = t('users.messages.removed')
    else
      flash[:alert] = @user.errors.full_messages
    end
    redirect_to users_url, status: :see_other
  end

  private

  def get_user
    @user = User.find(params[:id])
  end

  def user_params
    allowed_params  = [:username, :email, :password, :password_confirmation]
    allowed_params += [:is_enabled, :is_admin] if current_user.is_admin?
    params.require(:user).permit allowed_params
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <div class="card-body">
    <%= errors @user %>

    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

        <div class="form-group">
          <%= form.label :username, class: 'control-label' %>
          <div class="input-group mb-3">
            <%= form.text_field :username, class: 'form-control', autocomplete: 'off', placeholder: t('users.form.placeholder.username'), required: true %>
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fa fa-user" style="font-size: 18px;"></span>
              </div>
            </div>
          </div>
        </div>

        <% if current_user.is_admin? %>
          <div class="form-group row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <div class="custom-control custom-switch float-left mt-2 float-lg-right">
                <%= form.check_box :is_enabled, class: 'form-control custom-control-input' %>
                <%= form.label :is_enabled, class: 'control-label custom-control-label text-muted' %>
              </div>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <div class="custom-control custom-switch float-left mt-2 float-lg-right">
                <%= form.check_box :is_admin, class: 'form-control custom-control-input' %>
                <%= form.label :is_admin, class: 'control-label custom-control-label text-muted' %>
              </div>
            </div>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :email, class: 'control-label' %>
          <div class="input-group mb-3">
            <%= form.text_field :email, autofocus: true, class: 'form-control', autocomplete: 'off', placeholder: t('users.form.placeholder.email'), required: true %>
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fa fa-envelope"></span>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= form.label :password, class: 'control-label' %>
          <div class="input-group mb-3">
            <%= form.password_field :password, class: 'form-control', autocomplete: 'new-password', placeholder: t('users.form.placeholder.password') %>
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fa fa-lock" style="font-size: 18px;"></span>
              </div>
            </div>
          </div>
          <small class="text-muted"><%= t 'users.form.password-blank' %></small>
        </div>

        <div class="form-group">
          <%= form.label :password_confirmation, class: 'control-label' %>
          <div class="input-group mb-3">
            <%= form.password_field :password_confirmation, class: 'form-control', autocomplete: 'new-password', placeholder:  t('users.form.placeholder.password-confirmation') %>
            <div class="input-group-append">
              <div class="input-group-text">
                <span class="fa fa-lock" style="font-size: 18px;"></span>
              </div>
            </div>
          </div>
          <small class="text-muted"><%= t 'users.form.password-blank' %></small>
        </div>
      </div>
    </div>
  </div>

  <div class="card-footer">
    <div class="form-action">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <%= link_to t('actions.list'), users_path, class: 'btn btn-secondary' if current_user.is_admin? %>

          <div class="float-right">
            <%= form.submit (%w(edit update).include?(action_name) ? t('actions.update') : t('actions.save')), class: 'btn btn-primary' %>
            <%= link_to t('actions.show'), @user, class: 'btn btn-default' if %w(edit update).include?(action_name) %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<!-- Content -->
<section class="content pt-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-12 col-xs-12">
        <div class="card card-primary">
          <div class="card-header">
            <span class="card-title"><%= t 'users.form.title.edit' %></span>
          </div>
          
          <%= render 'form', user: @user %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<!-- Content Header -->
<% if current_user.is_admin? %>
  <section class="content-header pt-4">
    <div class="container">
      <div class="row mb-2">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <h1 class="m-0 float-left"><%= t 'users.actions.list' %></h1>
          <%= link_to t('users.actions.new'), new_user_path, class: 'btn btn-primary float-right' %>
        </div>
      </div>
    </div>
  </section>

  <!-- Content -->
  <section class="content">
    <div class="container" id="users-list">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <table class="table">
            <thead>
              <tr>
                <th><%= t('users.attributes.username') %></th>
                <th class="d-none d-sm-table-cell"><%= t('users.attributes.email') %></th>
                <th class="d-none d-sm-table-cell"><%= t('users.attributes.is_admin') %></th>
                <th><%= t('users.attributes.is_enabled') %></th>
                <th><span class="sr-only"><%= t('actions.actions') %></span></th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.username %></td>
                  <td class="d-none d-sm-table-cell"><%= user.email %></td>
                  <td class="d-none d-sm-table-cell"><%= t "#{user.is_admin}" %></td>
                  <td><%= t "#{user.is_enabled}" %></td>
                  <td class="col-1 text-nowrap">
                    <div class="float-right">
                      <%= link_to '', user_path(user), class: 'mx-1 fa fa-eye', title: t('users.actions.show') %>
                      <%= link_to '', edit_user_path(user), class: 'mx-1 fa fa-edit', title: t('users.actions.edit') %>
                      <%= link_to '', user_path(user), data: { turbo_method: :delete, turbo_confirm: t('users.actions.confirm-destroy')%{user: user.username} }, class: 'mx-1 text-danger fa fa-times', title: t('users.actions.destroy') %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="paginate">
            <small><%= page_entries_info @users, entry_name: '' %></small>
            <div class="pagination pagination-sm">
              <%= paginate @users %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/users/new.html.erb
<!-- Content -->
<section class="content pt-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-12 col-xs-12">
        <div class="card card-primary">
          <div class="card-header">
            <span class="card-title"><%= t 'users.form.title.new' %></h3>
          </div>
          
          <%= render 'form', user: @user %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<!-- Content -->
<section class="content pt-2">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card card-primary">
          <div class="card-header">
            <span class="card-title"><%= @user.username %></h3>
          </div>

          <div class="card-body">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <dl class="row">
                <dt class="col-sm-3"><%= t 'users.attributes.email' %></dt>
                <dd class="col-sm-9"><%= @user.email %></dd>

                <dt class="col-sm-3"><%= t 'users.attributes.is_admin' %></dt>
                <dd class="col-sm-9"><%= t @user.is_admin %></dd>

                <dt class="col-sm-3"><%= t 'users.attributes.is_enabled' %></dt>
                <dd class="col-sm-9"><%= t @user.is_enabled %></dd>

                <dt class="col-sm-3"><%= t 'users.attributes.sign_in_count' %></dt>
                <dd class="col-sm-9"><%= @user.sign_in_count %></dd>

                <dt class="col-sm-3"><%= t 'users.attributes.current_sign_in_at' %></dt>
                <dd class="col-sm-9"><%= @user.current_sign_in_at.present? ? @user.current_sign_in_at : '---' %></dd>

                <dt class="col-sm-3"><%= t 'users.attributes.current_sign_in_ip' %></dt>
                <dd class="col-sm-9"><%= @user.current_sign_in_ip.present? ? @user.current_sign_in_ip : '---' %></dd>

                <dt class="col-sm-3"><%= I18n.t('users.attributes.created_urls') %></dt>
                <dd class="col-sm-9"><%= @user.urls.collect{|u| link_to(u.name, url_url(u))}.join(', ').html_safe %></dd>

                <dt class="col-sm-3"><%= I18n.t('users.attributes.created_tags') %></dt>
                <dd class="col-sm-9"><%= @user.tags.collect{|t| link_to(t.name, tag_url(t))}.join(', ').html_safe %></dd>
              </dl>
            </div>
          </div>

          <div class="card-footer">
            <div class="form-action">
              <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  
                  <%= link_to t('actions.list'), users_path, class: 'btn btn-secondary' if current_user.is_admin? %>

                  <div class="float-right">
                    <%= link_to t('actions.edit'), edit_user_path(@user), class: 'btn btn-primary' %>
                    <%= link_to t('users.actions.destroy'), user_path(@user), data: { turbo_method: :delete, turbo_confirm: t('users.actions.confirm-destroy')%{user: @user.username} }, class: 'btn btn-danger', title: t('users.actions.destroy') if current_user.is_admin? %>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
    <%= render partial: 'comments/comments', locals: {object: @user} %>
  </div>
</section>