config/routes.rb
require 'admin_domain'

Rails.application.routes.draw do
  # Callback for omniauth oauth2
  constraints AdminDomain do
    devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  end
  scope "(:locale)", locale: /en|es/, defaults: {locale: :es} do
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines paths for admin mode
    constraints AdminDomain do
      devise_for :users, skip: :omniauth_callbacks
      #devise_for :users
      get 'admin', to: 'admin#index'
      resources :comments, only: [:create]
      resources :tags
      resources :urls do
        collection do
          get 'reload_slug'
        end
      end
      resources :users
    end

    # Defines the root path route ("/")
    root 'home#index'

    # Links routes
    get '/:slug', to: 'home#redirect', constraints: AppDomain
  end
end

app/models/tag.rb
#--
#
#################################################################################
# Shortener: Generate, use, manage and analyze short URLs.
# Copyright 2023 Santiago Ramos
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#################################################################################
#
#++

class Tag < ApplicationRecord
  has_and_belongs_to_many :urls
  has_many :visits, through: :urls
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :created_by, class_name: 'User'
  belongs_to :updated_by, class_name: 'User', optional: true

  validates :name, presence: true, uniqueness: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.reorder(:name).page params[:page]
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.created_by = current_user
    if @tag.save
      flash[:notice] = t('tags.messages.created')
      redirect_to @tag
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @tag.updated_by = current_user
    if @tag.update(tag_params)
      flash[:notice] = t('tags.messages.updated')
      redirect_to @tag
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @tag.destroy
    if @tag.errors.empty?
      flash[:notice] = t('tags.messages.removed')
    else
      flash[:alert] = @tag.errors.full_messages
    end
    redirect_to tags_url, status: :see_other
  end

  private

  def get_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name, :description)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <div class="card-body">
    <%= errors @tag %>

    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

        <div class="form-group row">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <%= form.text_field :name, class: 'form-control form-control-border', autocomplete: 'off', placeholder: t('tags.form.placeholder.name'), required: true %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <%= form.text_area :description, class: 'form-control form-control-border', autocomplete: 'off', placeholder: t('tags.form.placeholder.description'), required: false %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="card-footer">
    <div class="form-action">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <%= link_to t('actions.list'), tags_path, class: 'btn btn-secondary' %>

          <div class="float-right">
            <%= form.submit (%w(edit update).include?(action_name) ? t('actions.update') : t('actions.save')), class: 'btn btn-primary' %>
            <%= link_to t('actions.show'), @tag, class: 'btn btn-default' if %w(edit update).include?(action_name) %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/tags/edit.html.erb
<!-- Content -->
<section class="content pt-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-12 col-xs-12">
        <div class="card card-primary">
          <div class="card-header">
            <span class="card-title"><%= t 'tags.form.title.edit' %></h3>
          </div>
          
          <%= render 'form', tag: @tag %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/tags/index.html.erb
<!-- Content Header -->
<% if current_user %>
  <section class="content-header pt-4">
    <div class="container">
      <div class="row mb-2">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <h1 class="m-0 float-left"><%= t 'tags.actions.list' %></h1>
          <%= link_to t('tags.actions.new'), new_tag_path, class: 'btn btn-primary float-right' %>
        </div>
      </div>
    </div>
  </section>

  <!-- Content -->
  <section class="content">
    <div class="container" id="users-list">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <table class="table">
            <thead>
              <tr>
                <th><%= t('tags.attributes.name') %></th>
                <th><%= t('tags.attributes.created_by') %></th>
                <th><span class="sr-only"><%= t('actions.actions') %></span></th>
              </tr>
            </thead>
            <tbody>
              <% @tags.each do |tag| %>
                <tr>
                  <td><%= tag.name %></td>
                  <td><%= tag.created_by&.username %></td>
                  <td class="col-1 text-nowrap">
                    <div class="float-right">
                      <%= link_to '', tag_path(tag), class: 'mx-1 fa fa-eye', title: t('tags.actions.show') %>
                      <%= link_to '', edit_tag_path(tag), class: 'mx-1 fa fa-edit', title: t('tags.actions.edit') %>
                      <%= link_to '', tag_path(tag), data: { turbo_method: :delete, turbo_confirm: t('tags.actions.confirm-destroy')%{tag: tag.name} }, class: 'mx-1 text-danger fa fa-times', title: t('tags.actions.destroy') %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="paginate">
            <small><%= page_entries_info @tags, entry_name: '' %></small>
            <div class="pagination pagination-sm">
              <%= paginate @tags %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/tags/new.html.erb
<!-- Content -->
<section class="content pt-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 offset-lg-3 col-md-8 offset-md-2 col-sm-12 col-xs-12">
        <div class="card card-primary">
          <div class="card-header">
            <span class="card-title"><%= t 'tags.form.title.new' %></h3>
          </div>
          
          <%= render 'form', tag: @tag %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/tags/show.html.erb
<!-- Content -->
<section class="content pt-2">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card card-primary">
          <div class="card-header">
            <span class="card-title"><%= t('models.tag.one') + ': ' + @tag.name %></h3>
          </div>

          <div class="card-body">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <dl class="row">
                <dt class="col-sm-3"><%= I18n.t('tags.attributes.description') %></dt>
                <dd class="col-sm-9"><%= @tag.description || '---' %></dd>

                <dt class="col-sm-3"><%= I18n.t('tags.attributes.used_on') %></dt>
                <dd class="col-sm-9"><%= @tag.urls.collect{|u| link_to(u.name, url_url(u))}.join(', ').html_safe %></dd>

                <dt class="col-sm-3"><%= I18n.t('tags.attributes.created_by') %></dt>
                <dd class="col-sm-9">
                  <% if @tag.created_by %>
                    <%= current_user.is_admin? ? link_to(@tag.created_by.username, user_url(@tag.created_by)) : @tag.created_by.username %>
                  <% else %>
                    <%= I18n.t('users.messages.unknown-user') %>
                  <% end %>
                </dd>

                <dt class="col-sm-3"><%= I18n.t('tags.attributes.created_at') %></dt>
                <dd class="col-sm-9"><%= I18n.l(@tag.created_at) %></dd>

                <% if @tag.updated_by_id %>
                  <dt class="col-sm-3"><%= I18n.t('tags.attributes.updated_by') %></dt>
                  <dd class="col-sm-9"><%= @tag.updated_by&.username || '---' %></dd>

                  <dt class="col-sm-3"><%= I18n.t('tags.attributes.updated_at') %></dt>
                  <dd class="col-sm-9"><%= I18n.l(@tag.updated_at) %></dd>
                <% end %>
              </dl>
            </div>
          </div>

          <div class="card-footer">
            <div class="form-action">
              <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  
                  <%= link_to t('actions.list'), tags_path, class: 'btn btn-secondary' %>

                  <div class="float-right">
                    <%= link_to t('actions.edit'), edit_tag_path(@tag), class: 'btn btn-primary' %>
                    <%= link_to t('tags.actions.destroy'), tag_path(@tag), data: { turbo_method: :delete, turbo_confirm: t('tags.actions.confirm-destroy')%{tag: @tag.name} }, class: 'btn btn-danger', title: t('tags.actions.destroy') %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= render partial: 'visits/statistics', locals: {object: @tag} %>
    <%= render partial: 'comments/comments', locals: {object: @tag} %>
  </div>
</section>